version: '3.4'

services:
  sqldata:
   image:  mcr.microsoft.com/mssql/server:2019-latest
   environment:
    - SA_PASSWORD=luboy#2022
    - ACCEPT_EULA=Y
   ports:
    - "1450:1433"
    
  futbol:
    image: ${DOCKER_REGISTRY-}futbol
    build:
      context: .
      dockerfile: Futbol/Dockerfile
